spring.application.name=alerts

logging.config=classpath:log4j2.xml

# Niveau de log par défaut (override par log4j2.xml)
logging.level.root=INFO

data.original.path=C:/Users/User/Documents/Alternance/OpenClassrooms/Projet5/SafetyNet-SpringBoot/src/main/resources/data.json
data.updated.path=C:/Users/User/Documents/Alternance/OpenClassrooms/Projet5/SafetyNet-SpringBoot/src/main/resources/data_updated.json

data.persistence.enabled=true